[build]
  # Publish directory (where your built site files are located)
  publish = "."
  
  # Build command (not needed for static HTML site)
  command = ""

[build.environment]
  # Environment variables (if needed)
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true